In [13]:
import numpy as np

In [ ]:
### 차원

In [62]:
a = [1, 2, 3] # 형태 (1, 3) => (, 3) 튜플에러 => (3, )
array1 = np.array(a)

print('array1 type: ', type(array1))
print('array1의 형태', array1.shape)
print(f'array1은 {array1.ndim}차원')

array1 type:  <class 'numpy.ndarray'>
array1의 형태 (3,)
array1은 1차원


In [63]:
# 2차원의 사례
a2 = [[1, 2, 3], [11, 22, 33]] # 형태 (2, 3)
array2d = np.array(a2)

print('array2d type: ', type(array2d))
print('array2d의 형태', array2d.shape)
print(f'array2d은 {array2d.ndim}차원')

array2d type:  <class 'numpy.ndarray'>
array2d의 형태 (2, 3)
array2d은 2차원


In [7]:
# 3차원의 사례
a3 = [[[4, 5, 6]],[[1, 2, 3]]] # 형태 (2, 1, 3)
array3d = np.array(a3)

print('array3d type: ', type(array3d))
print('array3d의 형태', array3d.shape)
print(f'array3d은 {array3d.ndim}차원')

array3d type:  <class 'numpy.ndarray'>
array3d의 형태 (2, 1, 3)
array3d은 3차원


### ndarray 편리하게 생성 - arange, zeros, ones

In [25]:
# arange
# seq_array = np.arange(start=1, stop=11)
seq_array = np.arange(1, 11)
print(seq_array)
print(seq_array.dtype) # 해당 array 의 데이터 타입
print(seq_array.shape)

[ 1  2  3  4  5  6  7  8  9 10]
int32
(10,)


In [45]:
# zeros 로 0으로 된 행렬을 생성
zero_array = np.zeros((2, 4), dtype='int32') # dtype을 int32
print(zero_array)
print(zero_array.dtype) # 해당 array 의 데이터 타입
print(zero_array.shape)

[[0 0 0 0]
 [0 0 0 0]]
int32
(2, 4)


In [44]:
# ones 로 1로 된 행렬을 생성
one_array = np.ones((3, 2), dtype='int64') # dtype을 int64
print(one_array)
print(one_array.dtype) # 해당 array 의 데이터 타입
print(one_array.shape)

[[1 1]
 [1 1]
 [1 1]]
int64
(3, 2)


array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

### reshape의 사용 예시

In [42]:
# seq_array = [1 2 3 4 5 6 7 8 9 10] 
# 1차원인 seq_array 를 2 차원 배열로 바꿔줌
# 요소 숫자를 맞춰줘야함
seq_array.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### numpy의 dtype 살펴보기

In [66]:
# numpy 의 데이터 타입은 다 같은 타입으로 구성된다.
l2 = [1, 2, 'test']

# np.array를 활용하여 ndarray로 변환
array_l2 = np.array(l2)
print(array_l2, array_l2.dtype)
l3 = [1, 2, 5.5]
array_l3 = np.array(l3)
print(array_l3, array_l3.dtype)

['1' '2' 'test'] <U11
[1.  2.  5.5] float64


In [61]:
# dtype의 상호 변환 => astype
array_int = np.array([1, 3, 5])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# array_float => array_int2
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

# 자료에 따른 버림현상
array_float2 = np.array([1.1, 2.2, 3.3])
# int로 바뀌면 소숫점이 버려진다.

array_int3 = array_float2.astype('int32') 
print(array_int3)

[1. 3. 5.] float64
[1 3 5] int32
[1 2 3]
