In [51]:
import numpy as np

### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
*넘파이에서 ndarray내의 일부 데이터 셋이나 특정 데이터만을 선택 할 수 있도록 하는 인덱싱에 대한 알기

#### 1.특정한 데이터만 추출

#### 2.슬라이싱(Slicing)

#### 3.팬시 인덱싱(Fancy Indexing)

#### 4.불린 인덱싱(Boolean Indexing)

In [9]:
# 1~9까지 1차원 ndarray생성 - np.arange

array1 = np.arange(1, 10)
print(array1)
value = array1[-1]

print('value: ', value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
value:  9
<class 'numpy.int32'>


In [17]:
# array1을 2차원으로 변형

array1d = array1.copy()
array2d = array1d.reshape(3, -1)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 1. 특정 데이터만 추출

In [22]:
print('(row=0, col=0) index 가리키는 값: ', array2d[0, 0])
print('(row=0, col=0) index 가리키는 값: ', array2d[0][0])
print('(row=0, col=0) index 가리키는 값: ', array2d[0][1])
print('(row=0, col=0) index 가리키는 값: ', array2d[0, 1])

(row=0, col=0) index 가리키는 값:  1
(row=0, col=0) index 가리키는 값:  1
(row=0, col=0) index 가리키는 값:  2
(row=0, col=0) index 가리키는 값:  2


### 2. 슬라이싱(Slicing) - 2차원

In [32]:
print(array2d)

print('array2d[0:2, 0:2]:\n', array2d[0:2, 0:2])

print('array2d[1:3, 0:3]:\n', array2d[1:, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]:
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]:
 [[4 5 6]
 [7 8 9]]


In [35]:
## question 1

print('array2d (:2, 0):\n', array2d[:2, 0])  # 1차원 출력
print('array2d (:2, 0:1):\n', array2d[:2, 0:1])  # 2차원 출력

array2d (:2, 0):
 [1 4]
array2d (:2, 0:1):
 [[1]
 [4]]


### 3. 팬시 인덱싱(Fancy Indexing)

In [38]:
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
# 팬시 인덱싱은 각 열과 행을 선택해서 뽑아올 수 있다.

# 1차원

print(array2d[[0, 1], 1])  # array2d 의 0, 1열의 1행만 뽑아온다.
print(array2d[[0, 1], [0, 1]])  # array2d 의 0, 1열의 0, 1행만 뽑아온다.

print(array2d[[0, 2], 2])  # array2d 의 0, 2열의 2행만 뽑아온다.
print(array2d[[0, 2], [0, 2]])  # array2d 의 0, 2열의 0, 2행만 뽑아온다.

# 2차원

print(array2d[[0, 2], 2:])  # array2d 의 0, 2열의 2행부터 끝까지 뽑아온다.

print(array2d[[0, 2], ::2])  # array2d 의 0, 2열의 첫 행부터 끝 행까지 2칸씩 띄어서 뽑아온다.
# print(array2d[::2, ::2]) 위와 같음

[2 5]
[1 5]
[3 9]
[1 9]
[[3]
 [9]]
[[1 3]
 [7 9]]
